### ISSUE TITLE
Error at first run

### ISSUE THREAD

**Issue by metinkun** [pushy-me/pushy-demo-react-native#14]
this error comes after npm run android.

![image](https://user-images.githubusercontent.com/34644243/120904679-1f53ba00-c656-11eb-81f8-bda4a1e75074.png)

**Comment by pushy** [comment]
Hi @metinkun,
This error does not have to do with the Pushy Demo project directly.

Please ensure you are running a Metro server by running the following command in the demo project directory:

```
react-native start
```

Please let us know if you face any issues.
