### ISSUE TITLE
how to call a function when received a notification when the app is in foreground

### ISSUE THREAD

**Issue by santhosh-keyworks** [pushy-me/pushy-demo-react-native#18]
When a notification is received how can we call another function to update the state inside the app without clicking the notification on the panel like firebase notification which gives listener when the app is in foreground we execute some logic to update the state directly.

**Comment by pushy** [comment]
Hi @santhosh-keyworks,
We'd be glad to assist with your inquiry.

To access and update a `Component` state when a notification is received and the app is in foreground, please modify your `App.js` as follows:

1. Add the following line of code after the `import` statements: 

```
let appInstance;
```

2. Add the following line of code after `super(props);` inside your `App` component's `constructor` method:

```
// Make component accessible to callbacks
appInstance = this;
```

3. Add the following line inside the `Pushy.setNotificationListener` and/or `Pushy.setNotificationClickListener` callback methods, updating the state accordingly:

```
// Update state from notification callbacks
appInstance && appInstance.setState({ message: data.message });
```

Please let us know if you face any issues.
