### ISSUE TITLE
Unable to resolve host "api.pushy.me": No address associated with hostname

### ISSUE THREAD

**Issue by creditcoder** [pushy-me/pushy-demo-react-native#3]
I can't run this project. I'm not sure what's the problem.

Unable to resolve host "api.pushy.me": No address associated with hostname
<unknown>
    
__invokeCallback
    F:\zzz\pushy-demo-react-native-master\node_modules\react-native\Libraries\ART\ReactNativeART.js:301:18
<unknown>
    
__guard
    F:\zzz\pushy-demo-react-native-master\node_modules\react-native\Libraries\ART\ReactNativeART.js:226:10
invokeCallbackAndReturnFlushedQueue
    F:\zzz\pushy-demo-react-native-master\node_modules\react-native\Libraries\ART\ReactNativeART.js:61:3
invokeCallbackAndReturnFlushedQueue
    [native code]

**Comment by pushy-me** [comment]
Hi @creditcoder,
We'd be glad to assist.

This error indicates the device is having trouble connecting to the Internet, or to your ISP's DNS servers, or may indicate an issue with your local network components (e.g. router).

Please ensure the device has a reliable Internet connection with a reachable DNS server, and try again.
