### ISSUE TITLE
How to implement a foreground service in React Native

### ISSUE THREAD

**Issue by OrrinHatch** [pushy-me/pushy-demo-react-native#43]
The article mentions that it is possible to implement a foreground service to solve the issue of not receiving messages. I am an Android beginner.
https://support.pushy.me/hc/en-us/articles/360043864791-Why-do-some-Chinese-devices-fail-to-receive-notifications-in-the-background
https://support.pushy.me/hc/en-us/articles/8961466967437-How-can-I-enable-foreground-service-functionality-on-Android

**Comment by OrrinHatch** [comment]
My application is primarily for Chinese users.

**Comment by pushy** [comment]
Hi @OrrinHatch,
Thanks for reaching out. We'd be glad to assist with your inquiry.

Please follow the instructions mentioned in the [How can I enable foreground service functionality on Android?
 ](https://support.pushy.me/hc/en-us/articles/8961466967437-How-can-I-enable-foreground-service-functionality-on-Android) support center article to enable foreground service functionality for your React Native Android app. The instructions apply to React Native projects as well.

Please let us know if there's anything else we can help with.
