### ISSUE TITLE
How to receive messages when App is killed

### ISSUE THREAD

**Issue by rahulchhabra07** [pushy-me/pushy-demo-react-native#6]
We had been using FCM data messages. However, in some android phone manufacturers, the receiving of data messages is cancelled by OS when the app has been killed by the user.

Does Pushy handle this use-case. If yes, how to proceed?

**Comment by pushy** [comment]
Hi @rahulchhabra07,
We'd be glad to assist with your inquiry.

Pushy uses MQTT to deliver data-only messages to your Android app, and executes your React Native JS code in Headless JS to handle the notification, as long as the native `JobService` that establishes the MQTT connection is still alive.

We offer the option of enabling [FCM high-priority fallback delivery](https://pushy.me/docs/resources/fcm-fallback-delivery) to support some manufacturers that like to terminate app services when your app goes to background. However, with FCM fallback delivery, FCM data messages are sent, and not notification messages.

Do you have a list of Android phone manufacturers that can receive FCM notification messages, but not FCM data messages, when your app is in the background?

**Comment by rahulchhabra07** [comment]
Hi,

Do you have nay examples of Headless Task along w Pushy?

Also, we are using react-native-background-fetch that uses the native JobSheduler library.

We were facing particular issues with OnePlus phones. They are not receiving FCM data messages when a user swipes to kill the app.

We'll check high priority FCM message delivery once.

Thanks.

**Comment by pushy** [comment]
Hi @rahulchhabra07,
Our React Native docs & SDK already support using a headless JS task to receive notifications in the background using the following code (placed in `App.js` outside a `Component` class):

```
// Please place this code in App.js,
// After the import statements, and before the Component class

Pushy.setNotificationListener(async (data) => {
    // Print notification payload data
    console.log('Received notification: ' + JSON.stringify(data));

    // Notification title
    let notificationTitle = 'MyApp';

    // Attempt to extract the "message" property from the payload: {"message":"Hello World!"}
    let notificationText = data.message || 'Test notification';

    // Display basic system notification
    Pushy.notify(notificationTitle, notificationText, data);
});
```

Please give our [FCM fallback delivery](https://pushy.me/docs/resources/fcm-fallback-delivery) a try to see if the OnePlus phones can receive the notification or not, and let us know. If not, we'll investigate if using FCM notification messages works on OnePlus devices.

**Comment by rahulchhabra07** [comment]
This worked perfectly. Thanks.
