### ISSUE TITLE
Can't run project

### ISSUE THREAD

**Issue by Topdev826** [pushy-me/pushy-demo-react-native#8]
Hi, how are you?
I am new in React-native.. but I know a little how to install and build project. So I have followed your instructions to build pushy project ,but I can't run project.
The error message is as followings:

Unable to load script. Make sure you're either running a Metro server(run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.

My node version is 14.13.1

Please let me know what is problem...
I will wait response any time.

**Comment by Topdev826** [comment]
I have added screenshot as a photo.
![Screenshot at Mar 25 13-46-35](https://user-images.githubusercontent.com/58735336/112527039-9aecdd00-8d70-11eb-9bab-3b4c36f542e3.png)

**Comment by pushy** [comment]
Hi @topDev826,
We'd be glad to assist.

Unfortunately, this error is not directly related to the Pushy React Native SDK. Your app running on your device is not able to reach the RN Metro server, which is a React Native executable that is supposed to be running on your development machine, which servers the client app a `.js` bundle.

Please attempt the various solutions mentioned here:
https://stackoverflow.com/questions/44446523/unable-to-load-script-from-assets-index-android-bundle-on-windows

**Comment by Topdev826** [comment]
Thanks for your reply.
I have already attempted with this, but it doesn't work.
I have built other react-native apps and samples, but only this demo project doesn't work.
If you can't understand my word, I can send video recording.
Please let me know correct way.

**Comment by pushy** [comment]
Hi @topDev826,
It's possible that it's related to your installed version of the React-Native CLI.

Please try running this command to install version `4.9.0`:

```
npm install -g react-native@4.9.0
```

Then, try running `react-native run-android` again.
